### ISSUE TITLE
有个小问题

### ISSUE THREAD

**Issue by whoma** [Megan-TA/dom-diff-demo#1]
https://github.com/Megan-TA/dom-diff-demo/blob/fcf24030e6863b6cddb04b7476568c6edca1179b/src/element.js#L35

会不会应该这样了？
 let tagName = node.tagName.toLowerCase()

**Comment by Megan-TA** [comment]
> [dom-diff-demo/src/element.js](https://github.com/Megan-TA/dom-diff-demo/blob/fcf24030e6863b6cddb04b7476568c6edca1179b/src/element.js#L35)
> 
> Line 35 in [fcf2403](/Megan-TA/dom-diff-demo/commit/fcf24030e6863b6cddb04b7476568c6edca1179b)
> 
>  let tagName = node[key].tagName.toLowerCase() 
> 会不会应该这样了？
> let tagName = node.tagName.toLowerCase()

这都被你发现了 厉害！
已修复
谢谢

**Comment by whoma** [comment]
没事，相互学习
